name: Create Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm ci

      - name: Build extension
        run: npm run build

      - name: Create release package
        id: package
        run: ./.github/workflows/scripts/create-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ steps.package.outputs.version }}"
          name: "Release v${{ steps.package.outputs.version }}"
          body_path: .github/workflows/templates/release-body.md
          files: ./${{ steps.package.outputs.filename }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
